title: Técnicas de Programación
author: Luz E. Over V.
description: Guía teorico-práctica sobre Técnicas de programación
logo: https://github.com/OverCV.png

execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

launch_buttons:
  binderhub_url: ""
  colab_url: https://colab.research.google.com

repository:
  url: https://github.com/OverCV/ADA-Help
  branch: main

html:
  favicon: _static/favicon.ico
  use_favicon: true
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  html:
  extra_css:
    - "/docs/_static/custom.css"
  comments:
    hypothesis: true
